server:
  port: 8083

spring:
  application:
    name: travel-manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel_manage?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 40
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
