server:
  port: 8083

spring:
  application:
    name: travel-manage
  datasource:
    url: jdbc:h2:tcp://localhost/~/travel_manage
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path : /swagger-ui.html